language: node_js
node_js:
  - '0.12'
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - 'npm i' # install npm packages
after_script:
  - 'npm run travis'
  - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'